#!/usr/bin/env python3

# Copyright (c) 2026 Adam G. Sweeney <agsweeney@gmail.com>
# SPDX-License-Identifier: BSD-3-Clause
"""Convert an .mplc package to an embeddable C source file for NetBurner firmware."""

import argparse
import pathlib
import sys


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=pathlib.Path, help="Input .mplc file")
    parser.add_argument("output", type=pathlib.Path, help="Output .c file")
    parser.add_argument("--symbol", default="g_embedded_mplc", help="Array symbol name")
    args = parser.parse_args()

    data = args.input.read_bytes()
    if len(data) == 0:
        print("error: empty input", file=sys.stderr)
        return 1

    lines = [
        "/*",
        " * Copyright (c) 2026 Adam G. Sweeney <agsweeney@gmail.com>",
        " * SPDX-License-Identifier: BSD-3-Clause",
        " *",
        " * Auto-generated by mplc_to_carray.py — do not edit.",
        " */",
        "#include <stdint.h>",
        "",
        f"const uint8_t {args.symbol}[] = {{",
    ]

    row = "    "
    for i, byte in enumerate(data):
        row += f"0x{byte:02X}, "
        if (i + 1) % 12 == 0:
            lines.append(row.rstrip())
            row = "    "
    if row.strip():
        lines.append(row.rstrip().rstrip(","))

    lines.append("};")
    lines.append(f"const uint32_t {args.symbol}_size = {len(data)}U;")
    lines.append("")

    args.output.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {args.output} ({len(data)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
